"""update db

Revision ID: 25ac49dfe877
Revises: 
Create Date: 2019-03-16 15:24:25.564355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ac49dfe877'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OCR', sa.Column('character', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OCR', 'character')
    # ### end Alembic commands ###
